### ISSUE TITLE
A typo in environment setup instructions?

### ISSUE THREAD

**Issue by yanxingp** [computer-networks/liso-starter-code#1]
Hi,

I was just following the docker setup instructions, and I think in step 4:

**run docker run -it -v <absolute_path_to_current_folder>/15-441-project-1/:/home/15-441-project-1/ --name <name_for_your_container> project1 /bin/bash**

the image name should be **15441project1** instead of **project1**.

**Comment by pengyun961012** [comment]
Yes that is correct, I will fix the README to reflect this, thanks for pointing this out!

**Comment by justinemarie** [comment]
Last year I would have given away a t-shirt for finding a bug and filing an issue or PR... no T-shirts this year... need to find an alternative... all the same: thanks!!
